version: "3"
services:
  app:
    build:
      context: .
    env_file: ./.env
    # network_mode: "host"
    restart: on-failure
    expose:
      - "3030"
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - "3030:3030"
    depends_on:
      - mysqldb
    environment:
      MYSQL_HOST: mysqldb
    command: npm start

  mysqldb:
    image: mysql
    env_file: ./.env
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: $MYSQL_DBNAME
      MYSQL_USER: $MYSQL_USER
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql

volumes:
  mysql:
  mysql_config:
